services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongodb
    volumes:
      - ${PWD}/:/cadti/

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: client-dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ${PWD}/client/:/cadti/client/
    #stdin_open: true

  mongodb:
    container_name: mongodb
    image: mongo:4.2-bionic
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    container_name: pg_container
    image: postgres:12.13
    restart: on-failure
    environment:
      POSTGRES_USER: svom
      POSTGRES_PASSWORD: mengo
      POSTGRES_DB: sismob_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:
  mongo_data:
