services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongodb
    volumes:
      - ${PWD}/:/cadti/

  mongodb:
    container_name: mongodb
    image: mongo:4.2-bionic
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    container_name: pg_container
    image: postgres:12.13
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: on-failure
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
    external: true
  pgadmin_data:
    external: true
  mongo_data:
    external: true
