export const dischargedForm = [
    { field: "veiculoId", label: "Número" },
    { field: "placa", label: "Placa" },
    { field: "renavam", label: "RENAVAM" },
    { field: "utilizacao", label: "Utilização" },
    { field: "codigoEmpresa", label: "Código" },
    { field: "empresa", label: "Delegatário" },
    { field: "dataRegistro", label: "Data de Registro" },
    { field: "situacao", label: "Situação" },
    { field: "dataBaixa", label: "Data baixa" },
    { field: "nChassi", label: "Número chassi" },
    { field: "marcaChassi", label: "Marca chassi" },
    { field: "modeloChassi", label: "Modelo chassi" },
    { field: "anoChassi", label: "Ano chassi" },
    { field: "valorChassi", label: "Valor Chassi" },
    { field: "marcaCarroceria", label: "Marca carroceria" },
    { field: "modeloCarroceria", label: "Modelo carroceria" },
    { field: "anoCarroceria", label: "Ano carroceria" },
    { field: "indicadorIdade", label: "Indicador de Idade" },
    { field: "valorCarroceria", label: "Valor carroceria" },
    { field: "dominio", label: "Leasing" },
    { field: "delegatarioCompartilhado", label: "Empresas autorizadas a compartilhar" },
    { field: "cores", label: "Cores" },
    { field: "seguradora", label: "Seguradora" },
    { field: "apolice", label: "Apólice" },
    { field: "dataEmissao", label: "Data Inicio" },
    { field: "vencimento", label: "Data Fim", },
    { field: "empresaLaudo", label: "Empresa Laudo", },
    { field: "numeroLaudo", label: "Número Laudo", },
    { field: "validade", label: "Validade Laudo", },
    { field: "cilindros", label: "Cilindros" },
    { field: "potencia", label: "Potência" },
    { field: "eixos", label: "Eixos" },
    { field: 'pneumaticosDianteiros', label: 'Pneumáticos Dianteiros', },
    { field: 'pneumaticosTraseiros', label: 'Pneumáticos Traseiros', },
    { field: "pesoDianteiro", label: "Peso Dianteiro" },
    { field: "pesoTraseiro", label: "Peso Traseiro" },
    { field: "pbt", label: "PBT" },
    { field: "poltronas", label: "Poltronas" },
    { field: "piquesPoltrona", label: "Piques Poltrona" },
    { field: "distanciaMinima", label: "Distância Mínima" },
    { field: "distanciaMaxima", label: "Distância Máxima" },
    { field: "equipamentos", label: "Equipamentos" },
    { field: "acessibilidade", label: "Acessibilidade" },
    { field: "sipro", label: "SIPRO" },
    { field: "obs", label: "Observação" }
]

export const allBaixadoFields = [
    "Número", "Placa", "RENAVAM", "Data de Registro", "Utilização", "Código", "Delegatário", "Leasing", "Seguradora", "Apólice", "Data Inicio", "Data Fim",
    "Empresa Laudo", "Número Laudo", "Validade Laudo", "Empresas autorizadas a compartilhar", "Poltronas", "Eixos", "PBT", "Marca chassi", "Modelo chassi",
    "Ano chassi", "Número chassi", "Valor Chassi", "Situação", "Data baixa", "SIPRO", "Cilindros", "Potência", "Marca carroceria", "Modelo carroceria",
    "Ano carroceria", "Valor carroceria", "Piques Poltrona", "Peso Dianteiro", "Peso Traseiro", "Cores", "Equipamentos", "Observação", "Indicador de Idade",
    "Distância Mínima", "Distância Máxima", "__v", "id"
]
